name: testing
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_bloc: ^2.1.1
  url_launcher: ^5.4.2
  font_awesome_flutter: ^8.2.0
  carousel_slider: ^1.3.0
  chewie: ^0.9.10

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/images/profile_photo.jpg
    - lib/images/Screenshot (109).jpg
    - lib/images/Screenshot (104).jpg
    - lib/images/Screenshot (105).jpg
    - lib/images/Screenshot (106).jpg
    - lib/images/Screenshot (107).jpg
    - lib/images/Screenshot (108).jpg
    - lib/images/festnight.jpg
    - lib/images/robokriti.jpg
    - lib/images/Screenshot (112).jpg
    - lib/images/informals.jpg
    - lib/images/pixels.jpg
    - lib/images/enigma.jpg
    - lib/images/techprastuti.jpg
    - lib/images/codezilla.jpg
    - lib/images/incognito.jpg
    - lib/images/bizgyan.jpg
    - lib/images/techneeti.jpg
    - lib/images/world.jpg
    - lib/images/cyber.jpg
    - lib/images/app.jpg
    - lib/images/bridge_design.jpg
    - lib/images/ai.jpg
    - lib/images/campus.jpg
    - lib/images/shresth.jpg
    - lib/images/kshitiz.jpg
    - lib/images/krishna.jpg
    - lib/images/pratyush.jpg
    - lib/images/debansho.jpg
    - lib/images/arpit.jpg
    - lib/images/prince.jpg
    - lib/images/prajjawal_jaiswal.jpg
    - lib/images/ayushi_verma.jpg
    - lib/images/arima.jpg
    - lib/images/akansha.jpg
    - lib/images/chitrakshi.jpg
    - lib/images/ruchi.jpg
    - lib/images/prajjawal_singh.jpg
    - lib/images/danish.jpg
    - lib/images/yashi.jpg
    - lib/images/swapnil_gupta.jpg
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  - family: Pacifico
    fonts:
    - asset: fonts/Pacifico-Regular.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
